[package]
name = "test_mode"
version = "0.1.0"
authors = ["RCS team <us@pdx.com>"]

[[bin]]
name = "rcs_sw"
path = "../common/main.rs"

[lib]
name = "libs"
path = "src/lib.rs"

[dependencies]
timer = "0.1.6"
libc = "0.2"
time = "0.1"
i2cdev = "*"
byteorder = "0.5"
